# Generated by Django 5.2.7 on 2026-09-22 07:44

import biblioteca.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nacionalidad', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('cargo', models.CharField(choices=[('BIBLIOTECARIO', 'Bibliotecario/a'), ('ASISTENTE', 'Asistente'), ('ADMINISTRADOR', 'Administrador/a')], default='ASISTENTE', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='JuegoMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='ejemplares disponibles')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=biblioteca.models.ruta_portada, verbose_name='portada')),
                ('nombre', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=80, verbose_name='marca / editorial')),
                ('categoria', models.CharField(choices=[('ESTRATEGIA', 'Estrategia'), ('FAMILIAR', 'Familiar'), ('PARTY', 'Party'), ('INFANTIL', 'Infantil')], max_length=12)),
                ('jugadores_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='jugadores (mínimo)')),
                ('jugadores_max', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='jugadores (máximo)')),
                ('edad_minima', models.PositiveSmallIntegerField(verbose_name='edad mínima')),
            ],
            options={
                'verbose_name': 'juego de mesa',
                'verbose_name_plural': 'juegos de mesa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='ejemplares disponibles')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=biblioteca.models.ruta_portada, verbose_name='portada')),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('isbn', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^[0-9-]{10,17}$', 'El ISBN solo admite números y guiones (10 a 17 caracteres).')], verbose_name='ISBN')),
                ('anio_publicacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1450)], verbose_name='año de publicación')),
                ('tipo', models.CharField(choices=[('FISICO', 'Físico'), ('EBOOK', 'Ebook')], editable=False, max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='biblioteca.autor')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='LibroEbook',
            fields=[
                ('libro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.libro')),
                ('formato_archivo', models.CharField(choices=[('EPUB', 'EPUB'), ('PDF', 'PDF'), ('MOBI', 'MOBI')], default='EPUB', max_length=10)),
                ('tamano_mb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='tamaño (MB)')),
            ],
            options={
                'verbose_name': 'ebook',
                'verbose_name_plural': 'ebooks',
            },
            bases=('biblioteca.libro',),
        ),
        migrations.CreateModel(
            name='LibroFisico',
            fields=[
                ('libro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.libro')),
                ('ubicacion', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='ubicación en estantería')),
            ],
            options={
                'verbose_name': 'libro físico',
                'verbose_name_plural': 'libros físicos',
            },
            bases=('biblioteca.libro',),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(validators=[django.core.validators.MinLengthValidator(5, 'La opinión debe tener al menos 5 caracteres.')], verbose_name='opinión')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='biblioteca.libro')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='foto de perfil')),
                ('descripcion', models.CharField(blank=True, max_length=280, verbose_name='descripción')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3)])),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,12}$', 'Ingresa un teléfono válido, por ejemplo +56912345678.')], verbose_name='teléfono')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, help_text='Cuenta con la que este socio inicia sesión (opcional). Permite que vea sus propios préstamos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'socio',
                'verbose_name_plural': 'socios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('fecha_devolucion_prevista', models.DateField(editable=False)),
                ('fecha_devolucion_real', models.DateField(blank=True, editable=False, null=True)),
                ('devuelto', models.BooleanField(default=False, editable=False)),
                ('empleado', models.ForeignKey(blank=True, help_text='Vacío cuando el socio pide el préstamo desde el portal, sin pasar por el mesón.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='biblioteca.empleado')),
                ('juego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='biblioteca.juegomesa')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='biblioteca.libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.socio')),
            ],
            options={
                'verbose_name': 'préstamo',
                'verbose_name_plural': 'préstamos',
                'ordering': ['-fecha_prestamo', '-pk'],
            },
        ),
    ]
