# Generated by Django 5.2.7 on 2026-09-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libroebook',
            options={'ordering': ['titulo'], 'verbose_name': 'ebook', 'verbose_name_plural': 'ebooks'},
        ),
        migrations.AlterModelOptions(
            name='librofisico',
            options={'ordering': ['titulo'], 'verbose_name': 'libro físico', 'verbose_name_plural': 'libros físicos'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['usuario__username'], 'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
    ]
